// firstAidData.js — hardcoded first-aid content (no DB). Malayalam-first.
// Each situation: category, name, signs, numbered steps, what NOT to do, call number.

export const FA_CATEGORIES = [
  { key: 'cardiac', ml: 'ഹൃദയം', en: 'Cardiac', icon: '🫀' },
  { key: 'breathing', ml: 'ശ്വാസം', en: 'Breathing', icon: '🫁' },
  { key: 'bleeding', ml: 'രക്തസ്രാവം', en: 'Bleeding', icon: '🩸' },
  { key: 'poisoning', ml: 'വിഷബാധ', en: 'Poisoning', icon: '☠️' },
  { key: 'burns', ml: 'പൊള്ളൽ', en: 'Burns', icon: '🔥' },
  { key: 'fractures', ml: 'ഒടിവ്', en: 'Fractures', icon: '🦴' },
  { key: 'choking', ml: 'ശ്വാസംമുട്ടൽ', en: 'Choking', icon: '😳' },
  { key: 'drowning', ml: 'മുങ്ങൽ', en: 'Drowning', icon: '🌊' },
  { key: 'seizure', ml: 'അപസ്മാരം', en: 'Seizure', icon: '⚡' },
  { key: 'diabetic', ml: 'പ്രമേഹ അടിയന്തരം', en: 'Diabetic', icon: '🍬' },
  { key: 'other', ml: 'മറ്റുള്ളവ', en: 'Other', icon: '➕' }
];

export const FIRST_AID = [
  { slug: 'heart-attack', category: 'cardiac', name_ml: 'ഹൃദയാഘാതം', name_en: 'Heart Attack', call: '108',
    signs_ml: ['നെഞ്ചുവേദന/ഭാരം', 'കൈ, താടി, മുതുകിലേക്ക് വേദന', 'വിയർപ്പ്, ശ്വാസംമുട്ടൽ'],
    signs_en: ['Chest pain or pressure', 'Pain to arm, jaw or back', 'Sweating, breathlessness'],
    steps_ml: ['ഉടൻ 108 വിളിക്കുക', 'വ്യക്തിയെ ഇരുത്തി വിശ്രമിപ്പിക്കുക', 'ഇറുകിയ വസ്ത്രം അയയ്ക്കുക', 'അലർജിയില്ലെങ്കിൽ ആസ്പിരിൻ ചവച്ചു കൊടുക്കാം (ഡോക്ടർ പറഞ്ഞിട്ടുണ്ടെങ്കിൽ)', 'ബോധം/ശ്വാസം നിന്നാൽ CPR തുടങ്ങുക'],
    steps_en: ['Call 108 immediately', 'Sit the person down and keep them calm', 'Loosen tight clothing', 'Give aspirin to chew if no allergy (if previously advised)', 'If unresponsive and not breathing, start CPR'],
    donts_ml: ['ഒറ്റയ്ക്ക് വാഹനമോടിക്കാൻ അനുവദിക്കരുത്', 'ഭക്ഷണം/വെള്ളം കൊടുക്കരുത്'],
    donts_en: ['Do not let them drive themselves', 'Do not give food or water'] },
  { slug: 'cardiac-arrest-cpr', category: 'cardiac', name_ml: 'ഹൃദയസ്തംഭനം (CPR)', name_en: 'Cardiac Arrest (CPR)', call: '108',
    signs_ml: ['ബോധമില്ല', 'ശ്വാസമില്ല/സാധാരണമല്ല', 'നാഡിമിടിപ്പില്ല'],
    signs_en: ['Unconscious', 'Not breathing normally', 'No pulse'],
    steps_ml: ['108 വിളിക്കുക, സഹായം തേടുക', 'നെഞ്ചിന്റെ മധ്യത്തിൽ രണ്ട് കൈകൊണ്ട് ശക്തിയായി അമർത്തുക', 'മിനിറ്റിൽ 100-120 തവണ, 5 സെ.മീ ആഴത്തിൽ', 'നിർത്താതെ തുടരുക; സഹായം എത്തുന്നത് വരെ', 'AED ലഭ്യമെങ്കിൽ ഉപയോഗിക്കുക'],
    steps_en: ['Call 108 and get help', 'Push hard in the centre of the chest with both hands', '100-120 pushes per minute, about 5 cm deep', 'Do not stop until help arrives', 'Use an AED if available'],
    donts_ml: ['അമർത്തൽ ഇടയ്ക്കിടെ നിർത്തരുത്', 'പരിശീലനമില്ലെങ്കിൽ വായ്-വായ് ശ്വാസം നിർബന്ധമല്ല'],
    donts_en: ['Do not interrupt compressions', 'Mouth-to-mouth is optional if untrained'] },
  { slug: 'choking-adult', category: 'choking', name_ml: 'ശ്വാസംമുട്ടൽ (മുതിർന്നവർ)', name_en: 'Choking (Adult)', call: '108',
    signs_ml: ['സംസാരിക്കാനോ ചുമയ്ക്കാനോ കഴിയുന്നില്ല', 'കഴുത്തിൽ കൈ പിടിക്കുന്നു', 'മുഖം നീലനിറം'],
    signs_en: ['Cannot speak or cough', 'Clutching the throat', 'Face turning blue'],
    steps_ml: ['ചുമയ്ക്കാൻ പ്രോത്സാഹിപ്പിക്കുക', 'മുതുകിന്റെ മുകളിൽ 5 തവണ ശക്തിയായി അടിക്കുക', 'വയറിന് മുകളിൽ 5 തവണ ഉള്ളിലേക്ക്-മുകളിലേക്ക് അമർത്തുക (ഹൈംലിക്)', 'വസ്തു പുറത്ത് വരുന്നത് വരെ ആവർത്തിക്കുക', 'ബോധം പോയാൽ 108 വിളിച്ച് CPR'],
    steps_en: ['Encourage them to cough', 'Give 5 firm back blows between the shoulder blades', 'Give 5 abdominal thrusts (Heimlich)', 'Repeat until the object comes out', 'If they collapse, call 108 and start CPR'],
    donts_ml: ['വിരൽ ഇട്ട് കുത്തിയെടുക്കാൻ ശ്രമിക്കരുത്'],
    donts_en: ['Do not do blind finger sweeps'] },
  { slug: 'choking-infant', category: 'choking', name_ml: 'ശ്വാസംമുട്ടൽ (ശിശു)', name_en: 'Choking (Infant)', call: '108',
    signs_ml: ['കരയാൻ/ശ്വസിക്കാൻ കഴിയുന്നില്ല', 'മുഖം നീലനിറം'],
    signs_en: ['Cannot cry or breathe', 'Face turning blue'],
    steps_ml: ['കുഞ്ഞിനെ കമിഴ്ത്തി കൈയിൽ കിടത്തുക, തല താഴ്ത്തുക', 'മുതുകിൽ 5 തവണ മൃദുവായി അടിക്കുക', 'നെഞ്ചിൽ 2 വിരൽകൊണ്ട് 5 തവണ അമർത്തുക', 'ആവർത്തിക്കുക; 108 വിളിക്കുക'],
    steps_en: ['Lay the baby face-down along your arm, head low', 'Give 5 gentle back blows', 'Give 5 chest thrusts with 2 fingers', 'Repeat and call 108'],
    donts_ml: ['വയറിൽ അമർത്തരുത് (ശിശുവിന്)'],
    donts_en: ['Do not do abdominal thrusts on an infant'] },
  { slug: 'severe-bleeding', category: 'bleeding', name_ml: 'കടുത്ത രക്തസ്രാവം', name_en: 'Severe Bleeding', call: '108',
    signs_ml: ['അധിക രക്തസ്രാവം', 'വിളർച്ച, തലകറക്കം'],
    signs_en: ['Heavy bleeding', 'Pale, dizzy'],
    steps_ml: ['വൃത്തിയുള്ള തുണികൊണ്ട് നേരിട്ട് ശക്തിയായി അമർത്തുക', 'സാധ്യമെങ്കിൽ ഭാഗം ഹൃദയത്തിന് മുകളിലേക്ക് ഉയർത്തുക', 'തുണി നനഞ്ഞാൽ മുകളിൽ വീണ്ടും തുണി വയ്ക്കുക', '108 വിളിക്കുക'],
    steps_en: ['Press firmly on the wound with a clean cloth', 'Raise the part above heart level if possible', 'If soaked, add more cloth on top', 'Call 108'],
    donts_ml: ['ആദ്യ തുണി എടുത്തുമാറ്റരുത്', 'ആവശ്യമില്ലാതെ ടൂർണിക്കറ്റ് ഇടരുത്'],
    donts_en: ['Do not remove the first cloth', 'Avoid tourniquets unless trained'] },
  { slug: 'nosebleed', category: 'bleeding', name_ml: 'മൂക്കിൽ നിന്ന് രക്തം', name_en: 'Nosebleed', call: '112',
    signs_ml: ['മൂക്കിൽ നിന്ന് രക്തസ്രാവം'],
    signs_en: ['Bleeding from the nose'],
    steps_ml: ['മുന്നോട്ട് ചാഞ്ഞ് ഇരിക്കുക', 'മൂക്കിന്റെ മൃദുഭാഗം 10 മിനിറ്റ് അമർത്തിപ്പിടിക്കുക', 'വായിലൂടെ ശ്വസിക്കുക'],
    steps_en: ['Sit and lean forward', 'Pinch the soft part of the nose for 10 minutes', 'Breathe through the mouth'],
    donts_ml: ['തല പിന്നിലേക്ക് ചായ്ക്കരുത്'],
    donts_en: ['Do not tilt the head back'] },
  { slug: 'burns', category: 'burns', name_ml: 'പൊള്ളൽ', name_en: 'Burns', call: '108',
    signs_ml: ['ചുവപ്പ്, കുമിളകൾ, വേദന'],
    signs_en: ['Redness, blisters, pain'],
    steps_ml: ['20 മിനിറ്റ് ഒഴുകുന്ന തണുത്ത വെള്ളത്തിൽ കഴുകുക', 'ആഭരണങ്ങൾ/ഇറുകിയ വസ്ത്രം നീക്കുക', 'വൃത്തിയുള്ള നനവില്ലാത്ത തുണികൊണ്ട് മൂടുക', 'വലുതെങ്കിൽ 108 വിളിക്കുക'],
    steps_en: ['Cool under running water for 20 minutes', 'Remove jewellery/tight clothing', 'Cover with a clean, non-fluffy cloth', 'Call 108 if large or severe'],
    donts_ml: ['ഐസ്, ടൂത്ത്പേസ്റ്റ്, എണ്ണ പുരട്ടരുത്', 'കുമിളകൾ പൊട്ടിക്കരുത്'],
    donts_en: ['Do not apply ice, toothpaste or oil', 'Do not burst blisters'] },
  { slug: 'poisoning', category: 'poisoning', name_ml: 'വിഷബാധ (വിഴുങ്ങൽ)', name_en: 'Poisoning (Swallowed)', call: '108',
    signs_ml: ['ഛർദ്ദി, വയറുവേദന', 'ആശയക്കുഴപ്പം', 'വായിൽ പൊള്ളൽ'],
    signs_en: ['Vomiting, abdominal pain', 'Confusion', 'Burns around the mouth'],
    steps_ml: ['108 വിളിക്കുക; വിഷവസ്തുവിന്റെ പേര്/പാക്കറ്റ് കൈയിൽ വയ്ക്കുക', 'വായിലുള്ളത് പുറത്തെടുക്കുക', 'ബോധമുണ്ടെങ്കിൽ ഇടത് വശം ചരിച്ച് കിടത്തുക'],
    steps_en: ['Call 108; keep the poison name/packet', 'Remove anything left in the mouth', 'If conscious, lay them on their left side'],
    donts_ml: ['ഛർദ്ദിപ്പിക്കാൻ ശ്രമിക്കരുത് (നിർദ്ദേശമില്ലാതെ)', 'വെള്ളം/പാൽ കൊടുക്കരുത് (നിർദ്ദേശമില്ലാതെ)'],
    donts_en: ['Do not make them vomit unless told', 'Do not give water/milk unless advised'] },
  { slug: 'snake-bite', category: 'poisoning', name_ml: 'പാമ്പുകടി', name_en: 'Snake Bite', call: '108',
    signs_ml: ['കടിയേറ്റ പാടുകൾ', 'വീക്കം, വേദന', 'തലകറക്കം, ശ്വാസംമുട്ടൽ'],
    signs_en: ['Bite marks', 'Swelling, pain', 'Dizziness, breathlessness'],
    steps_ml: ['വ്യക്തിയെ ശാന്തമായി, ചലനമില്ലാതെ കിടത്തുക', 'കടിയേറ്റ ഭാഗം ഹൃദയത്തിന് താഴെ, ചലിപ്പിക്കാതെ', 'ആഭരണം/ഇറുകിയ വസ്ത്രം നീക്കുക', 'ഉടൻ 108 വിളിച്ച് ആശുപത്രിയിലെത്തിക്കുക'],
    steps_en: ['Keep the person calm and still', 'Keep the bitten part below heart level and immobile', 'Remove jewellery/tight items', 'Call 108 and get to hospital fast'],
    donts_ml: ['മുറിക്കുകയോ വലിച്ചൂറ്റുകയോ ചെയ്യരുത്', 'ഇറുകിയ കെട്ട് (ടൂർണിക്കറ്റ്) ഇടരുത്'],
    donts_en: ['Do not cut or suck the wound', 'Do not apply a tight tourniquet'] },
  { slug: 'seizure', category: 'seizure', name_ml: 'അപസ്മാരം (ചുഴലി)', name_en: 'Seizure', call: '108',
    signs_ml: ['ബോധം നഷ്ടം', 'ശരീരം വിറയ്ക്കൽ'],
    signs_en: ['Loss of awareness', 'Jerking movements'],
    steps_ml: ['ചുറ്റുമുള്ള അപകടകരമായ വസ്തുക്കൾ മാറ്റുക', 'തലയ്ക്ക് കീഴിൽ മൃദുവായത് വയ്ക്കുക', 'ചുഴലി കഴിഞ്ഞാൽ ഒരു വശം ചരിച്ച് കിടത്തുക', '5 മിനിറ്റിലേറെ നീണ്ടാൽ 108 വിളിക്കുക'],
    steps_en: ['Move dangerous objects away', 'Cushion the head', 'After it stops, roll them on their side', 'Call 108 if it lasts over 5 minutes'],
    donts_ml: ['വായിൽ ഒന്നും വയ്ക്കരുത്', 'ബലമായി പിടിച്ചു നിർത്തരുത്'],
    donts_en: ['Do not put anything in the mouth', 'Do not restrain them'] },
  { slug: 'drowning', category: 'drowning', name_ml: 'മുങ്ങൽ', name_en: 'Drowning', call: '108',
    signs_ml: ['വെള്ളത്തിൽ നിന്ന് രക്ഷിച്ചയാൾ', 'ശ്വാസമില്ല/ബോധമില്ല'],
    signs_en: ['Person rescued from water', 'Not breathing / unconscious'],
    steps_ml: ['സ്വന്തം സുരക്ഷ ഉറപ്പാക്കി വെള്ളത്തിൽ നിന്ന് കയറ്റുക', '108 വിളിക്കുക', 'ശ്വാസമില്ലെങ്കിൽ ഉടൻ CPR തുടങ്ങുക', 'നനഞ്ഞ വസ്ത്രം മാറ്റി ചൂട് നൽകുക'],
    steps_en: ['Get them out of water safely', 'Call 108', 'If not breathing, start CPR immediately', 'Remove wet clothes and keep warm'],
    donts_ml: ['വയറ്റിലെ വെള്ളം പുറത്തെടുക്കാൻ സമയം കളയരുത്'],
    donts_en: ['Do not waste time trying to drain water from the stomach'] },
  { slug: 'fracture', category: 'fractures', name_ml: 'എല്ലൊടിവ്', name_en: 'Fracture', call: '108',
    signs_ml: ['വേദന, വീക്കം', 'വളവ്/ചലിപ്പിക്കാൻ കഴിയായ്ക'],
    signs_en: ['Pain, swelling', 'Deformity / cannot move'],
    steps_ml: ['ഭാഗം ചലിപ്പിക്കാതെ അതേപടി നിർത്തുക (സ്പ്ലിന്റ്)', 'ഐസ് തുണിയിൽ പൊതിഞ്ഞ് വയ്ക്കുക', '108 വിളിക്കുക'],
    steps_en: ['Support and immobilise the part as found (splint)', 'Apply ice wrapped in cloth', 'Call 108'],
    donts_ml: ['ഒടിവ് നേരെയാക്കാൻ ശ്രമിക്കരുത്', 'ഭക്ഷണം കൊടുക്കരുത് (ശസ്ത്രക്രിയ വേണ്ടിവന്നാൽ)'],
    donts_en: ['Do not try to straighten the bone', 'Avoid food (surgery may be needed)'] },
  { slug: 'asthma-attack', category: 'breathing', name_ml: 'ആസ്ത്മ ആക്രമണം', name_en: 'Asthma Attack', call: '108',
    signs_ml: ['ശ്വാസംമുട്ടൽ, വിസിലടി', 'സംസാരിക്കാൻ ബുദ്ധിമുട്ട്'],
    signs_en: ['Breathlessness, wheezing', 'Difficulty speaking'],
    steps_ml: ['ഇരുന്ന് ശാന്തമായി ശ്വസിക്കാൻ സഹായിക്കുക', 'റിലീവർ ഇൻഹേലർ ഉപയോഗിക്കുക (ഓരോ പഫും)', 'മെച്ചപ്പെട്ടില്ലെങ്കിൽ 108 വിളിക്കുക'],
    steps_en: ['Help them sit up and breathe calmly', 'Use their reliever inhaler (puffs as prescribed)', 'If no improvement, call 108'],
    donts_ml: ['കിടത്തരുത്'],
    donts_en: ['Do not make them lie flat'] },
  { slug: 'anaphylaxis', category: 'breathing', name_ml: 'കടുത്ത അലർജി (അനാഫൈലാക്സിസ്)', name_en: 'Severe Allergy (Anaphylaxis)', call: '108',
    signs_ml: ['മുഖം/തൊണ്ട വീക്കം', 'ശ്വാസംമുട്ടൽ', 'ചർമ്മത്തിൽ തടിപ്പുകൾ'],
    signs_en: ['Face/throat swelling', 'Breathlessness', 'Widespread hives'],
    steps_ml: ['ഉടൻ 108 വിളിക്കുക', 'അഡ്രിനാലിൻ ഓട്ടോ-ഇൻജെക്ടർ ഉണ്ടെങ്കിൽ തുടയിൽ കുത്തുക', 'വ്യക്തിയെ പരന്ന് കിടത്തുക, കാൽ ഉയർത്തുക', 'ശ്വാസംമുട്ടിയാൽ ഇരുത്തുക'],
    steps_en: ['Call 108 immediately', 'Use an adrenaline auto-injector into the thigh if available', 'Lay flat and raise the legs', 'If breathing is hard, let them sit up'],
    donts_ml: ['ഒറ്റയ്ക്ക് വിടരുത്'],
    donts_en: ['Do not leave them alone'] },
  { slug: 'hypoglycemia', category: 'diabetic', name_ml: 'പഞ്ചസാര താഴൽ (ഹൈപ്പോ)', name_en: 'Low Blood Sugar', call: '108',
    signs_ml: ['വിറയൽ, വിയർപ്പ്', 'ആശയക്കുഴപ്പം', 'വിശപ്പ്'],
    signs_en: ['Shakiness, sweating', 'Confusion', 'Hunger'],
    steps_ml: ['ബോധമുണ്ടെങ്കിൽ പഞ്ചസാര/ജ്യൂസ്/മിഠായി കൊടുക്കുക', '15 മിനിറ്റിന് ശേഷം വീണ്ടും', 'മെച്ചപ്പെട്ടില്ലെങ്കിലോ ബോധം പോയാലോ 108'],
    steps_en: ['If conscious, give sugar/juice/sweets', 'Repeat after 15 minutes if needed', 'If no better or unconscious, call 108'],
    donts_ml: ['ബോധമില്ലാത്തയാൾക്ക് വായിലൂടെ ഒന്നും കൊടുക്കരുത്'],
    donts_en: ['Do not give anything by mouth if unconscious'] },
  { slug: 'hyperglycemia', category: 'diabetic', name_ml: 'പഞ്ചസാര ഉയരൽ', name_en: 'High Blood Sugar', call: '108',
    signs_ml: ['അമിത ദാഹം, ഇടയ്ക്കിടെ മൂത്രം', 'ക്ഷീണം, ആശയക്കുഴപ്പം'],
    signs_en: ['Excess thirst, frequent urination', 'Tiredness, confusion'],
    steps_ml: ['വെള്ളം കുടിക്കാൻ കൊടുക്കുക (ബോധമുണ്ടെങ്കിൽ)', 'ഡോക്ടറെ/108 ബന്ധപ്പെടുക', 'വേഗത്തിലുള്ള ശ്വാസം/ബോധക്ഷയം ഉണ്ടെങ്കിൽ അടിയന്തരം'],
    steps_en: ['Give water to drink (if conscious)', 'Contact a doctor / 108', 'Rapid breathing or drowsiness is an emergency'],
    donts_ml: ['ഇൻസുലിൻ അളവ് സ്വയം കൂട്ടരുത്'],
    donts_en: ['Do not adjust insulin dose on your own'] },
  { slug: 'electric-shock', category: 'other', name_ml: 'വൈദ്യുതാഘാതം', name_en: 'Electric Shock', call: '108',
    signs_ml: ['പൊള്ളൽ', 'ബോധക്ഷയം', 'ഹൃദയമിടിപ്പ് പ്രശ്നം'],
    signs_en: ['Burns', 'Unconsciousness', 'Heartbeat problems'],
    steps_ml: ['ആദ്യം വൈദ്യുതി ഓഫ് ചെയ്യുക', 'വരണ്ട തടി/പ്ലാസ്റ്റിക് കൊണ്ട് വ്യക്തിയെ ഉറവിൽ നിന്ന് അകറ്റുക', '108 വിളിക്കുക; ശ്വാസമില്ലെങ്കിൽ CPR'],
    steps_en: ['Switch off the power first', 'Separate the person from the source with dry wood/plastic', 'Call 108; start CPR if not breathing'],
    donts_ml: ['വൈദ്യുതി ഓഫ് ചെയ്യാതെ വ്യക്തിയെ തൊടരുത്'],
    donts_en: ['Do not touch the person before the power is off'] },
  { slug: 'heat-stroke', category: 'other', name_ml: 'സൂര്യാഘാതം', name_en: 'Heat Stroke', call: '108',
    signs_ml: ['ഉയർന്ന ശരീരതാപം', 'വരണ്ട ചൂടുള്ള ചർമ്മം', 'ആശയക്കുഴപ്പം'],
    signs_en: ['Very high body temperature', 'Hot, dry skin', 'Confusion'],
    steps_ml: ['തണുത്ത തണലിലേക്ക് മാറ്റുക', 'വസ്ത്രം അയച്ച് വെള്ളം/നനഞ്ഞ തുണികൊണ്ട് തണുപ്പിക്കുക', 'ബോധമുണ്ടെങ്കിൽ വെള്ളം കുടിക്കാൻ കൊടുക്കുക', '108 വിളിക്കുക'],
    steps_en: ['Move to a cool, shaded place', 'Loosen clothes and cool with water/wet cloths', 'Give water if conscious', 'Call 108'],
    donts_ml: ['അമിതമായി തണുപ്പിച്ച് വിറയൽ ഉണ്ടാക്കരുത്'],
    donts_en: ['Do not over-cool to the point of shivering'] },
  { slug: 'fainting', category: 'other', name_ml: 'ബോധക്ഷയം (മോഹാലസ്യം)', name_en: 'Fainting', call: '112',
    signs_ml: ['പെട്ടെന്ന് ബോധം നഷ്ടം', 'വിളർച്ച'],
    signs_en: ['Sudden brief loss of consciousness', 'Pale'],
    steps_ml: ['മലർത്തി കിടത്തി കാൽ ഉയർത്തുക', 'ശുദ്ധവായു ഉറപ്പാക്കുക', 'ബോധം വന്നാൽ പതിയെ എഴുന്നേൽപ്പിക്കുക', 'വേഗം ബോധം വന്നില്ലെങ്കിൽ 108'],
    steps_en: ['Lay flat and raise the legs', 'Ensure fresh air', 'Let them get up slowly when recovered', 'If not recovering quickly, call 108'],
    donts_ml: ['ഉടൻ എഴുന്നേൽപ്പിക്കരുത്'],
    donts_en: ['Do not stand them up immediately'] },
  { slug: 'stroke-fast', category: 'cardiac', name_ml: 'പക്ഷാഘാതം (FAST)', name_en: 'Stroke (FAST)', call: '108',
    signs_ml: ['മുഖം ഒരു വശം കോടൽ', 'കൈ ഉയർത്താൻ കഴിയായ്ക', 'സംസാരം കുഴയൽ'],
    signs_en: ['Face drooping on one side', 'Arm weakness', 'Slurred speech'],
    steps_ml: ['സമയം കുറിക്കുക — ലക്ഷണം തുടങ്ങിയത്', 'ഉടൻ 108 വിളിക്കുക', 'വ്യക്തിയെ സുഖമായി കിടത്തുക'],
    steps_en: ['Note the time symptoms started', 'Call 108 immediately', 'Keep the person comfortable'],
    donts_ml: ['ഭക്ഷണം/മരുന്ന്/വെള്ളം കൊടുക്കരുത്'],
    donts_en: ['Do not give food, medicine or water'] },
  { slug: 'eye-injury', category: 'other', name_ml: 'കണ്ണിന് പരിക്ക്', name_en: 'Eye Injury', call: '112',
    signs_ml: ['വേദന, ചുവപ്പ്', 'കാഴ്ച മങ്ങൽ'],
    signs_en: ['Pain, redness', 'Blurred vision'],
    steps_ml: ['രാസവസ്തുവാണെങ്കിൽ 15-20 മിനിറ്റ് വെള്ളംകൊണ്ട് കഴുകുക', 'കണ്ണ് തിരുമ്മരുത്', 'വൃത്തിയുള്ള തുണികൊണ്ട് മൃദുവായി മൂടുക', 'ഐ ഡോക്ടറെ കാണുക'],
    steps_en: ['If chemical, rinse with water for 15-20 minutes', 'Do not rub the eye', 'Cover gently with a clean cloth', 'See an eye doctor'],
    donts_ml: ['തറച്ച വസ്തു വലിച്ചെടുക്കരുത്'],
    donts_en: ['Do not remove an object stuck in the eye'] },
  { slug: 'head-injury', category: 'other', name_ml: 'തലയ്ക്ക് പരിക്ക്', name_en: 'Head Injury', call: '108',
    signs_ml: ['ബോധക്ഷയം', 'ഛർദ്ദി', 'ആശയക്കുഴപ്പം'],
    signs_en: ['Loss of consciousness', 'Vomiting', 'Confusion'],
    steps_ml: ['വ്യക്തിയെ അനക്കാതെ കിടത്തുക', 'രക്തസ്രാവം ഉണ്ടെങ്കിൽ മൃദുവായി അമർത്തുക', 'ബോധക്ഷയം/ഛർദ്ദി ഉണ്ടെങ്കിൽ 108'],
    steps_en: ['Keep the person still', 'If bleeding, press gently with a cloth', 'Call 108 if unconscious or vomiting'],
    donts_ml: ['കഴുത്ത് അനാവശ്യമായി അനക്കരുത്'],
    donts_en: ['Do not move the neck unnecessarily'] },
  { slug: 'sprain', category: 'fractures', name_ml: 'ഉളുക്ക്', name_en: 'Sprain', call: '112',
    signs_ml: ['വീക്കം, വേദന', 'ചലനത്തിൽ ബുദ്ധിമുട്ട്'],
    signs_en: ['Swelling, pain', 'Difficulty moving'],
    steps_ml: ['വിശ്രമം (Rest)', 'ഐസ് തുണിയിൽ (Ice)', 'ബാൻഡേജ് (Compression)', 'ഭാഗം ഉയർത്തുക (Elevation)'],
    steps_en: ['Rest', 'Ice (wrapped in cloth)', 'Compression bandage', 'Elevate the part'],
    donts_ml: ['ചൂട് വയ്ക്കരുത് (ആദ്യ ദിവസങ്ങളിൽ)'],
    donts_en: ['Do not apply heat in the first days'] },
  { slug: 'minor-cut', category: 'bleeding', name_ml: 'ചെറിയ മുറിവ്', name_en: 'Minor Cut', call: '112',
    signs_ml: ['ചെറിയ രക്തസ്രാവം'],
    signs_en: ['Small bleeding'],
    steps_ml: ['വൃത്തിയുള്ള വെള്ളംകൊണ്ട് കഴുകുക', 'വൃത്തിയുള്ള തുണികൊണ്ട് അമർത്തുക', 'ബാൻഡേജ് ഇടുക'],
    steps_en: ['Clean with clean water', 'Press with a clean cloth', 'Apply a bandage'],
    donts_ml: ['അഴുക്കുള്ള കൈകൊണ്ട് തൊടരുത്'],
    donts_en: ['Do not touch with dirty hands'] },
  { slug: 'dog-bite', category: 'poisoning', name_ml: 'നായ്ക്കടി', name_en: 'Dog/Animal Bite', call: '108',
    signs_ml: ['കടിയേറ്റ മുറിവ്', 'രക്തസ്രാവം'],
    signs_en: ['Bite wound', 'Bleeding'],
    steps_ml: ['മുറിവ് 15 മിനിറ്റ് സോപ്പും വെള്ളവുംകൊണ്ട് കഴുകുക', 'വൃത്തിയുള്ള തുണികൊണ്ട് മൂടുക', 'ഉടൻ ആശുപത്രിയിൽ — റാബീസ് കുത്തിവയ്പ്പ്'],
    steps_en: ['Wash the wound with soap and water for 15 minutes', 'Cover with a clean cloth', 'Go to hospital promptly for rabies vaccination'],
    donts_ml: ['മുറിവ് അവഗണിക്കരുത്'],
    donts_en: ['Do not ignore the wound'] },
  { slug: 'fever-child', category: 'other', name_ml: 'കുട്ടികളിലെ ഉയർന്ന പനി', name_en: 'High Fever in a Child', call: '108',
    signs_ml: ['ഉയർന്ന ശരീരതാപം', 'അലസത, ചൂട്'],
    signs_en: ['High temperature', 'Lethargy, hot skin'],
    steps_ml: ['വസ്ത്രം കുറയ്ക്കുക; നനഞ്ഞ തുണികൊണ്ട് തുടയ്ക്കുക', 'വെള്ളം/ദ്രാവകം കൊടുക്കുക', 'ഡോക്ടറുടെ നിർദ്ദേശപ്രകാരം പനി മരുന്ന്', 'ചുഴലി/ശ്വാസംമുട്ടൽ ഉണ്ടെങ്കിൽ 108'],
    steps_en: ['Remove extra clothing; sponge with lukewarm water', 'Give fluids', 'Give fever medicine as advised', 'Call 108 if seizure or breathing difficulty'],
    donts_ml: ['തണുത്ത വെള്ളം/ഐസ് കൊണ്ട് കുളിപ്പിക്കരുത്'],
    donts_en: ['Do not bathe in cold/ice water'] },
  { slug: 'foreign-body-ear-nose', category: 'other', name_ml: 'ചെവി/മൂക്കിൽ വസ്തു', name_en: 'Object in Ear/Nose', call: '112',
    signs_ml: ['അസ്വസ്ഥത', 'ചെവി/മൂക്കിൽ വസ്തു'],
    signs_en: ['Discomfort', 'Visible object in ear/nose'],
    steps_ml: ['മൂക്കിലാണെങ്കിൽ മറ്റേ ദ്വാരം അടച്ച് മൃദുവായി ഊതിക്കുക', 'എളുപ്പം എടുക്കാനാവുന്നില്ലെങ്കിൽ ഡോക്ടറെ കാണുക'],
    steps_en: ['For the nose, close the other nostril and blow gently', 'If not easily removed, see a doctor'],
    donts_ml: [' പിൻ/കൊട്ടി കൊണ്ട് കുത്തിയെടുക്കാൻ ശ്രമിക്കരുത്'],
    donts_en: ['Do not poke with pins or cotton buds'] },
  { slug: 'chemical-burn', category: 'burns', name_ml: 'രാസ പൊള്ളൽ', name_en: 'Chemical Burn', call: '108',
    signs_ml: ['ചർമ്മത്തിൽ എരിച്ചിൽ, ചുവപ്പ്'],
    signs_en: ['Burning, redness of skin'],
    steps_ml: ['മലിന വസ്ത്രം നീക്കുക', '20 മിനിറ്റോളം ഒഴുകുന്ന വെള്ളത്തിൽ കഴുകുക', '108 വിളിക്കുക; രാസവസ്തുവിന്റെ വിവരം കൈയിൽ വയ്ക്കുക'],
    steps_en: ['Remove contaminated clothing', 'Rinse under running water for about 20 minutes', 'Call 108; keep details of the chemical'],
    donts_ml: ['ന്യൂട്രലൈസ് ചെയ്യാൻ മറ്റ് രാസവസ്തുക്കൾ ഉപയോഗിക്കരുത്'],
    donts_en: ['Do not try to neutralise with other chemicals'] },
  { slug: 'shock', category: 'cardiac', name_ml: 'ഷോക്ക്', name_en: 'Shock', call: '108',
    signs_ml: ['വിളർച്ച, തണുത്ത വിയർപ്പ്', 'വേഗത്തിലുള്ള ദുർബല നാഡി', 'ആശയക്കുഴപ്പം'],
    signs_en: ['Pale, cold sweat', 'Fast weak pulse', 'Confusion'],
    steps_ml: ['മലർത്തി കിടത്തി കാൽ ഉയർത്തുക', 'ചൂട് നിലനിർത്തുക', '108 വിളിക്കുക', 'ശ്വാസം നിരീക്ഷിക്കുക'],
    steps_en: ['Lay flat and raise the legs', 'Keep them warm', 'Call 108', 'Monitor breathing'],
    donts_ml: ['ഭക്ഷണം/വെള്ളം കൊടുക്കരുത്'],
    donts_en: ['Do not give food or water'] }
];
