-- 0087_lab_test_guides.sql
-- Lab Test Guide — educational explanations of common lab tests. Additive only.
-- Educational only; app renders a non-dismissable disclaimer on every test page.
-- reviewed_by_doctor defaults false and is seeded false — content is NOT yet
-- doctor-reviewed (see BLOCKERS).

CREATE TABLE IF NOT EXISTS lab_test_guides (
  id                          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug                        varchar(255) UNIQUE NOT NULL,
  name_ml                     text,
  name_en                     text NOT NULL,
  abbreviation                varchar(20),
  category                    varchar(100),   -- blood|urine|imaging|heart|hormones|infection|cancer
  description_ml              text,
  description_en              text,
  what_it_measures_ml         text,
  what_it_measures_en         text,
  why_ordered_ml              text,
  why_ordered_en              text,
  preparation_ml              text,
  preparation_en              text,
  procedure_ml                text,
  procedure_en                text,
  normal_ranges               jsonb,
  abnormal_interpretation_ml  text,
  abnormal_interpretation_en  text,
  related_conditions          text[],
  related_tests               text[],
  is_published                boolean DEFAULT false,
  reviewed_by_doctor          boolean DEFAULT false,
  created_at                  timestamptz DEFAULT now(),
  updated_at                  timestamptz,
  deleted_at                  timestamptz
);

CREATE INDEX IF NOT EXISTS idx_labtests_category ON lab_test_guides (category) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_labtests_name_lower ON lab_test_guides (lower(name_en)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_labtests_abbr_lower ON lab_test_guides (lower(abbreviation)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_labtests_name_trgm ON lab_test_guides USING gin (name_en gin_trgm_ops) WHERE deleted_at IS NULL;

INSERT INTO lab_test_guides
  (slug, name_ml, name_en, abbreviation, category, description_ml, description_en,
   what_it_measures_en, why_ordered_en, preparation_en, procedure_en, normal_ranges,
   abnormal_interpretation_en, related_conditions, related_tests, is_published, reviewed_by_doctor)
VALUES
  ('complete-blood-count', 'സമ്പൂർണ രക്ത പരിശോധന', 'Complete Blood Count', 'CBC', 'blood',
   'രക്തത്തിലെ കോശങ്ങളുടെ എണ്ണവും അളവും പരിശോധിക്കുന്നു.', 'Measures the cells in your blood — red cells, white cells and platelets.',
   'Red blood cells, white blood cells, haemoglobin, haematocrit and platelet count.',
   'To screen for anaemia, infection, inflammation and many general health conditions.',
   'No special preparation; no fasting needed.', 'A small blood sample is drawn from a vein in the arm.',
   '{"haemoglobin_male":{"min":13.5,"max":17.5,"unit":"g/dL"},"haemoglobin_female":{"min":12.0,"max":15.5,"unit":"g/dL"},"wbc":{"min":4000,"max":11000,"unit":"cells/µL"},"platelets":{"min":150000,"max":410000,"unit":"cells/µL"}}',
   'Low haemoglobin may suggest anaemia; high white cells may suggest infection; low platelets may affect clotting.',
   ARRAY['Anaemia','Infection','Bleeding disorders'], ARRAY['ESR','Peripheral smear','Ferritin'], true, false),

  ('hba1c', 'എച്ച്ബിഎ1സി', 'Glycated Haemoglobin', 'HbA1c', 'blood',
   'കഴിഞ്ഞ 2-3 മാസത്തെ ശരാശരി രക്തത്തിലെ പഞ്ചസാര കാണിക്കുന്നു.', 'Shows your average blood sugar over the past 2–3 months.',
   'The percentage of haemoglobin coated with sugar (glucose).',
   'To diagnose and monitor diabetes and pre-diabetes.',
   'No fasting required; can be done any time of day.', 'A small blood sample is drawn from a vein.',
   '{"normal":{"max":5.7,"unit":"%"},"prediabetes":{"min":5.7,"max":6.4,"unit":"%"},"diabetes":{"min":6.5,"unit":"%"}}',
   'Higher values indicate poorer long-term blood-sugar control and higher diabetes risk.',
   ARRAY['Diabetes','Pre-diabetes'], ARRAY['Fasting Blood Glucose','Postprandial Glucose'], true, false),

  ('fasting-blood-glucose', 'ഫാസ്റ്റിംഗ് രക്തത്തിലെ പഞ്ചസാര', 'Fasting Blood Glucose', 'FBS', 'blood',
   'ഭക്ഷണം കഴിക്കാതെയുള്ള രക്തത്തിലെ പഞ്ചസാരയുടെ അളവ്.', 'Blood sugar level after an overnight fast.',
   'The amount of glucose in your blood after fasting.',
   'To screen for and monitor diabetes.',
   'Fast for 8–12 hours (water is allowed) before the test.', 'A blood sample is drawn from a vein.',
   '{"normal":{"min":70,"max":99,"unit":"mg/dL"},"prediabetes":{"min":100,"max":125,"unit":"mg/dL"},"diabetes":{"min":126,"unit":"mg/dL"}}',
   'High values may indicate diabetes; very low values may indicate hypoglycaemia.',
   ARRAY['Diabetes','Hypoglycaemia'], ARRAY['HbA1c','Postprandial Glucose'], true, false),

  ('postprandial-glucose', 'ഭക്ഷണശേഷമുള്ള പഞ്ചസാര', 'Postprandial Blood Glucose', 'PPBS', 'blood',
   'ഭക്ഷണം കഴിഞ്ഞ് 2 മണിക്കൂറിനുള്ള പഞ്ചസാര.', 'Blood sugar measured 2 hours after a meal.',
   'How well your body handles sugar after eating.',
   'To assess diabetes control alongside fasting sugar.',
   'Eat a normal meal, then test exactly 2 hours later.', 'A blood sample is drawn from a vein.',
   '{"normal":{"max":140,"unit":"mg/dL"},"prediabetes":{"min":140,"max":199,"unit":"mg/dL"},"diabetes":{"min":200,"unit":"mg/dL"}}',
   'High values 2 hours after eating may indicate diabetes or poor control.',
   ARRAY['Diabetes'], ARRAY['Fasting Blood Glucose','HbA1c'], true, false),

  ('lipid-profile', 'ലിപിഡ് പ്രൊഫൈൽ', 'Lipid Profile', 'Lipid', 'blood',
   'കൊളസ്ട്രോളും കൊഴുപ്പുകളും അളക്കുന്നു.', 'Measures cholesterol and other fats in your blood.',
   'Total cholesterol, LDL, HDL and triglycerides.',
   'To assess heart-disease risk.',
   'Fasting for 9–12 hours is usually advised.', 'A blood sample is drawn from a vein.',
   '{"total_cholesterol":{"max":200,"unit":"mg/dL"},"ldl":{"max":100,"unit":"mg/dL"},"hdl":{"min":40,"unit":"mg/dL"},"triglycerides":{"max":150,"unit":"mg/dL"}}',
   'High LDL/triglycerides and low HDL raise cardiovascular risk.',
   ARRAY['Heart disease','High cholesterol'], ARRAY['ECG','Blood Sugar'], true, false),

  ('tsh', 'ടിഎസ്എച്ച്', 'Thyroid Stimulating Hormone', 'TSH', 'hormones',
   'തൈറോയ്ഡ് പ്രവർത്തനം പരിശോധിക്കുന്നു.', 'Checks how well your thyroid gland is working.',
   'The level of thyroid-stimulating hormone from the pituitary gland.',
   'To detect an underactive or overactive thyroid.',
   'No fasting required; take at a consistent time if on thyroid medicine.', 'A blood sample is drawn from a vein.',
   '{"adult":{"min":0.4,"max":4.0,"unit":"mIU/L"}}',
   'High TSH suggests an underactive thyroid; low TSH suggests an overactive thyroid.',
   ARRAY['Hypothyroidism','Hyperthyroidism'], ARRAY['Thyroid Profile (T3/T4)'], true, false),

  ('thyroid-profile', 'തൈറോയ്ഡ് പ്രൊഫൈൽ', 'Thyroid Profile', 'T3 T4 TSH', 'hormones',
   'T3, T4, TSH എന്നിവ ഒരുമിച്ച് പരിശോധിക്കുന്നു.', 'Measures T3, T4 and TSH together to assess thyroid function.',
   'Triiodothyronine (T3), thyroxine (T4) and TSH.',
   'To fully evaluate thyroid disorders.',
   'No fasting required.', 'A blood sample is drawn from a vein.',
   '{"t3":{"min":80,"max":200,"unit":"ng/dL"},"t4":{"min":5.0,"max":12.0,"unit":"µg/dL"},"tsh":{"min":0.4,"max":4.0,"unit":"mIU/L"}}',
   'Patterns of T3/T4/TSH help distinguish types of thyroid disease.',
   ARRAY['Hypothyroidism','Hyperthyroidism'], ARRAY['TSH'], true, false),

  ('liver-function-test', 'കരൾ പ്രവർത്തന പരിശോധന', 'Liver Function Test', 'LFT', 'blood',
   'കരളിന്റെ ആരോഗ്യം പരിശോധിക്കുന്നു.', 'A group of tests that check how well your liver is working.',
   'Enzymes (SGOT/SGPT), bilirubin, albumin and total protein.',
   'To detect liver damage, hepatitis or jaundice.',
   'Fasting may be advised; follow your lab’s instructions.', 'A blood sample is drawn from a vein.',
   '{"sgpt_alt":{"min":7,"max":56,"unit":"U/L"},"sgot_ast":{"min":8,"max":48,"unit":"U/L"},"bilirubin_total":{"max":1.2,"unit":"mg/dL"}}',
   'Raised enzymes or bilirubin may indicate liver inflammation or blockage.',
   ARRAY['Hepatitis','Jaundice','Fatty liver'], ARRAY['Ultrasound Abdomen'], true, false),

  ('kidney-function-test', 'വൃക്ക പ്രവർത്തന പരിശോധന', 'Kidney Function Test', 'KFT', 'blood',
   'വൃക്കയുടെ ആരോഗ്യം പരിശോധിക്കുന്നു.', 'A group of tests that check how well your kidneys are working.',
   'Urea, creatinine, uric acid and electrolytes.',
   'To detect kidney disease and monitor kidney health.',
   'Follow your lab’s instructions; some labs advise fasting.', 'A blood sample is drawn from a vein.',
   '{"creatinine_male":{"min":0.7,"max":1.3,"unit":"mg/dL"},"creatinine_female":{"min":0.6,"max":1.1,"unit":"mg/dL"},"urea":{"min":15,"max":40,"unit":"mg/dL"}}',
   'Raised urea/creatinine may indicate reduced kidney function.',
   ARRAY['Kidney disease','Hypertension'], ARRAY['Creatinine','Urine Routine'], true, false),

  ('urine-routine', 'മൂത്ര പരിശോധന', 'Urine Routine Examination', 'Urine R/E', 'urine',
   'മൂത്രത്തിന്റെ പൊതു പരിശോധന.', 'A general examination of your urine for signs of infection or disease.',
   'Colour, protein, sugar, blood cells and bacteria in urine.',
   'To detect urinary infections, kidney problems and diabetes.',
   'Collect a clean mid-stream sample; morning sample preferred.', 'You provide a urine sample in a sterile container.',
   '{"protein":{"unit":"negative"},"glucose":{"unit":"negative"},"pus_cells":{"max":5,"unit":"/HPF"}}',
   'Protein, sugar, blood or pus cells in urine may indicate infection or kidney/diabetes issues.',
   ARRAY['Urinary tract infection','Kidney disease'], ARRAY['Urine Culture','KFT'], true, false),

  ('ecg', 'ഇസിജി', 'Electrocardiogram', 'ECG', 'heart',
   'ഹൃദയത്തിന്റെ വൈദ്യുത പ്രവർത്തനം രേഖപ്പെടുത്തുന്നു.', 'Records the electrical activity of your heart.',
   'Heart rate, rhythm and signs of strain or damage.',
   'To investigate chest pain, palpitations or heart rhythm problems.',
   'No special preparation; avoid oily skin creams on the chest.', 'Small sticky electrodes are placed on the chest, arms and legs for a few minutes.',
   NULL,
   'Abnormal patterns may indicate arrhythmia, prior heart attack or strain — interpreted by a doctor.',
   ARRAY['Arrhythmia','Heart attack','Angina'], ARRAY['Echocardiogram','Lipid Profile'], true, false),

  ('echocardiogram', 'എക്കോകാർഡിയോഗ്രാം', 'Echocardiogram', 'Echo', 'heart',
   'ഹൃദയത്തിന്റെ അൾട്രാസൗണ്ട് സ്കാൻ.', 'An ultrasound scan of your heart.',
   'The structure and pumping function of the heart and valves.',
   'To assess heart failure, valve problems and structural issues.',
   'No special preparation needed.', 'A probe with gel is moved over the chest to capture images.',
   NULL,
   'Reduced pumping (ejection fraction) or valve problems are interpreted by a cardiologist.',
   ARRAY['Heart failure','Valve disease'], ARRAY['ECG'], true, false),

  ('chest-xray', 'ചെസ്റ്റ് എക്സ്-റേ', 'Chest X-Ray', 'CXR', 'imaging',
   'നെഞ്ചിന്റെ എക്സ്-റേ ചിത്രം.', 'An X-ray image of your chest.',
   'The lungs, heart size and chest bones.',
   'To investigate cough, breathlessness, chest pain or infection.',
   'Remove metal objects; inform staff if you may be pregnant.', 'You stand against a plate while a quick X-ray image is taken.',
   NULL,
   'Shadows or changes may indicate infection, fluid or other lung conditions — read by a radiologist.',
   ARRAY['Pneumonia','Tuberculosis','Heart enlargement'], ARRAY['CBC','Sputum Test'], true, false),

  ('serum-creatinine', 'സീറം ക്രിയാറ്റിനിൻ', 'Serum Creatinine', 'Creatinine', 'blood',
   'വൃക്കയുടെ പ്രവർത്തനം സൂചിപ്പിക്കുന്നു.', 'A waste product that shows how well your kidneys filter blood.',
   'The level of creatinine, a muscle waste product cleared by the kidneys.',
   'To assess and monitor kidney function.',
   'No special preparation usually needed.', 'A blood sample is drawn from a vein.',
   '{"adult_male":{"min":0.7,"max":1.3,"unit":"mg/dL"},"adult_female":{"min":0.6,"max":1.1,"unit":"mg/dL"}}',
   'Higher creatinine suggests reduced kidney filtration.',
   ARRAY['Kidney disease'], ARRAY['KFT','Urea'], true, false),

  ('serum-uric-acid', 'സീറം യൂറിക് ആസിഡ്', 'Serum Uric Acid', 'Uric Acid', 'blood',
   'യൂറിക് ആസിഡിന്റെ അളവ്.', 'Measures uric acid, high levels of which can cause gout.',
   'The level of uric acid in the blood.',
   'To investigate joint pain (gout) and kidney stones.',
   'Fasting may be advised.', 'A blood sample is drawn from a vein.',
   '{"adult_male":{"min":3.4,"max":7.0,"unit":"mg/dL"},"adult_female":{"min":2.4,"max":6.0,"unit":"mg/dL"}}',
   'High uric acid may cause gout and kidney stones.',
   ARRAY['Gout','Kidney stones'], ARRAY['KFT'], true, false),

  ('vitamin-d', 'വിറ്റാമിൻ ഡി', 'Vitamin D (25-OH)', 'Vit D', 'blood',
   'വിറ്റാമിൻ ഡിയുടെ അളവ്.', 'Measures the level of vitamin D, important for bone health.',
   'The 25-hydroxy vitamin D level in your blood.',
   'To investigate bone pain, weakness or fatigue.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"deficient":{"max":20,"unit":"ng/mL"},"insufficient":{"min":20,"max":29,"unit":"ng/mL"},"sufficient":{"min":30,"max":100,"unit":"ng/mL"}}',
   'Low vitamin D is very common and may cause bone and muscle problems.',
   ARRAY['Vitamin D deficiency','Osteoporosis'], ARRAY['Serum Calcium'], true, false),

  ('vitamin-b12', 'വിറ്റാമിൻ ബി12', 'Vitamin B12', 'B12', 'blood',
   'വിറ്റാമിൻ ബി12യുടെ അളവ്.', 'Measures vitamin B12, needed for nerves and blood formation.',
   'The level of vitamin B12 in your blood.',
   'To investigate tiredness, numbness or anaemia.',
   'Fasting may be advised.', 'A blood sample is drawn from a vein.',
   '{"normal":{"min":200,"max":900,"unit":"pg/mL"}}',
   'Low B12 may cause anaemia and nerve symptoms; common in vegetarians.',
   ARRAY['B12 deficiency','Anaemia'], ARRAY['CBC'], true, false),

  ('serum-calcium', 'സീറം കാൽസ്യം', 'Serum Calcium', 'Calcium', 'blood',
   'രക്തത്തിലെ കാൽസ്യത്തിന്റെ അളവ്.', 'Measures calcium, important for bones, nerves and muscles.',
   'The level of calcium in your blood.',
   'To investigate bone, kidney or parathyroid problems.',
   'No special preparation usually needed.', 'A blood sample is drawn from a vein.',
   '{"adult":{"min":8.5,"max":10.5,"unit":"mg/dL"}}',
   'High or low calcium can affect bones, nerves and the heart.',
   ARRAY['Osteoporosis','Parathyroid disorders'], ARRAY['Vitamin D'], true, false),

  ('esr', 'ഇഎസ്ആർ', 'Erythrocyte Sedimentation Rate', 'ESR', 'blood',
   'ശരീരത്തിലെ വീക്കത്തിന്റെ സൂചന.', 'A general marker of inflammation in the body.',
   'How quickly red blood cells settle, which rises with inflammation.',
   'To detect inflammation or infection.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"adult_male":{"min":0,"max":15,"unit":"mm/hr"},"adult_female":{"min":0,"max":20,"unit":"mm/hr"}}',
   'A raised ESR is a non-specific sign of inflammation or infection.',
   ARRAY['Infection','Inflammation'], ARRAY['CRP','CBC'], true, false),

  ('crp', 'സിആർപി', 'C-Reactive Protein', 'CRP', 'infection',
   'വീക്കത്തിന്റെയും അണുബാധയുടെയും സൂചന.', 'A marker that rises quickly with inflammation and infection.',
   'The level of C-reactive protein made by the liver during inflammation.',
   'To detect and monitor infection or inflammation.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"normal":{"max":5,"unit":"mg/L"}}',
   'High CRP suggests active inflammation or infection.',
   ARRAY['Infection','Inflammation'], ARRAY['ESR','CBC'], true, false),

  ('blood-urea', 'രക്ത യൂറിയ', 'Blood Urea', 'Urea', 'blood',
   'വൃക്ക പ്രവർത്തനത്തിന്റെ സൂചന.', 'A waste product that reflects kidney function and hydration.',
   'The level of urea nitrogen in your blood.',
   'To assess kidney function and hydration.',
   'Follow your lab’s instructions.', 'A blood sample is drawn from a vein.',
   '{"adult":{"min":15,"max":40,"unit":"mg/dL"}}',
   'High urea may indicate reduced kidney function or dehydration.',
   ARRAY['Kidney disease','Dehydration'], ARRAY['Creatinine','KFT'], true, false),

  ('psa', 'പിഎസ്എ', 'Prostate Specific Antigen', 'PSA', 'cancer',
   'പ്രോസ്റ്റേറ്റ് ആരോഗ്യത്തിന്റെ സൂചന.', 'A blood marker used to screen for prostate problems in men.',
   'The level of prostate-specific antigen in the blood.',
   'To screen for prostate enlargement or cancer in men.',
   'Avoid ejaculation and vigorous cycling for 48 hours before.', 'A blood sample is drawn from a vein.',
   '{"normal":{"max":4.0,"unit":"ng/mL"}}',
   'Raised PSA can occur with prostate enlargement, infection or cancer — needs doctor review.',
   ARRAY['Prostate enlargement','Prostate cancer'], ARRAY['Ultrasound'], true, false),

  ('ca-125', 'സിഎ-125', 'Cancer Antigen 125', 'CA-125', 'cancer',
   'ഒരു ട്യൂമർ മാർക്കർ.', 'A tumour marker sometimes used in ovarian conditions.',
   'The level of CA-125 protein in the blood.',
   'To help monitor certain ovarian conditions and cancers.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"normal":{"max":35,"unit":"U/mL"}}',
   'Raised CA-125 can occur in ovarian and some other conditions — not a stand-alone diagnosis.',
   ARRAY['Ovarian conditions'], ARRAY['Ultrasound'], true, false),

  ('dengue-ns1', 'ഡെങ്കി എൻഎസ്1', 'Dengue NS1 Antigen', 'NS1', 'infection',
   'ഡെങ്കി പനി നേരത്തെ കണ്ടെത്താൻ.', 'Helps detect dengue infection in the early days of fever.',
   'The dengue NS1 antigen, present early in dengue infection.',
   'To diagnose dengue during fever, especially in Kerala’s monsoon season.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"result":{"unit":"positive/negative"}}',
   'A positive result supports dengue; results are interpreted with symptoms and platelet count.',
   ARRAY['Dengue fever'], ARRAY['CBC','Platelet Count'], true, false),

  ('widal-test', 'വിഡാൽ ടെസ്റ്റ്', 'Widal Test', 'Widal', 'infection',
   'ടൈഫോയ്ഡ് പനിയുടെ സൂചന.', 'A blood test that may support a diagnosis of typhoid fever.',
   'Antibodies against Salmonella typhi bacteria.',
   'To help diagnose typhoid fever.',
   'No special preparation needed.', 'A blood sample is drawn from a vein.',
   '{"titre":{"unit":"reported as titre"}}',
   'Rising antibody titres support typhoid; results must be read with symptoms and timing.',
   ARRAY['Typhoid fever'], ARRAY['Blood Culture','CBC'], true, false),

  ('serum-ferritin', 'സീറം ഫെറിറ്റിൻ', 'Serum Ferritin', 'Ferritin', 'blood',
   'ശരീരത്തിലെ ഇരുമ്പ് ശേഖരത്തിന്റെ സൂചന.', 'Reflects the amount of iron stored in your body.',
   'The level of ferritin, the body’s iron-storage protein.',
   'To investigate anaemia and iron deficiency or overload.',
   'Fasting may be advised.', 'A blood sample is drawn from a vein.',
   '{"male":{"min":30,"max":400,"unit":"ng/mL"},"female":{"min":15,"max":150,"unit":"ng/mL"}}',
   'Low ferritin indicates iron deficiency; very high levels may indicate inflammation or overload.',
   ARRAY['Iron-deficiency anaemia'], ARRAY['CBC','Vitamin B12'], true, false),

  ('serum-electrolytes', 'സീറം ഇലക്ട്രോലൈറ്റുകൾ', 'Serum Electrolytes', 'Electrolytes', 'blood',
   'സോഡിയം, പൊട്ടാസ്യം തുടങ്ങിയവയുടെ അളവ്.', 'Measures salts such as sodium and potassium that balance body fluids.',
   'Sodium, potassium and chloride levels.',
   'To assess hydration, kidney function and heart-rhythm risks.',
   'No special preparation usually needed.', 'A blood sample is drawn from a vein.',
   '{"sodium":{"min":135,"max":145,"unit":"mmol/L"},"potassium":{"min":3.5,"max":5.1,"unit":"mmol/L"},"chloride":{"min":98,"max":107,"unit":"mmol/L"}}',
   'Abnormal electrolytes can affect the heart, nerves and muscles.',
   ARRAY['Kidney disease','Dehydration'], ARRAY['KFT'], true, false),

  ('urine-culture', 'മൂത്ര കൾച്ചർ', 'Urine Culture', 'Urine C/S', 'infection',
   'മൂത്രത്തിലെ അണുബാധ കണ്ടെത്താൻ.', 'Identifies bacteria causing a urinary infection and the right antibiotic.',
   'Which bacteria (if any) are growing in the urine and their antibiotic sensitivity.',
   'To confirm a urinary tract infection and guide treatment.',
   'Collect a clean-catch mid-stream sample before starting antibiotics.', 'You provide a urine sample in a sterile container; it is cultured over 1–2 days.',
   '{"result":{"unit":"no growth / growth with sensitivity"}}',
   'Growth of bacteria confirms infection and guides antibiotic choice.',
   ARRAY['Urinary tract infection'], ARRAY['Urine Routine'], true, false),

  ('ultrasound-abdomen', 'വയറിന്റെ അൾട്രാസൗണ്ട്', 'Ultrasound Abdomen', 'USG Abdomen', 'imaging',
   'വയറിലെ അവയവങ്ങളുടെ സ്കാൻ.', 'An ultrasound scan of the organs in your abdomen.',
   'The liver, gallbladder, kidneys, pancreas and other abdominal organs.',
   'To investigate abdominal pain, stones, or organ problems.',
   'Fasting for 6–8 hours is often advised; a full bladder may be needed.', 'A probe with gel is moved over the abdomen to capture images.',
   NULL,
   'Findings such as stones, cysts or organ changes are interpreted by a radiologist.',
   ARRAY['Gallstones','Kidney stones','Fatty liver'], ARRAY['LFT','KFT'], true, false),

  ('hiv-test', 'എച്ച്ഐവി ടെസ്റ്റ്', 'HIV Test', 'HIV', 'infection',
   'എച്ച്ഐവി അണുബാധ പരിശോധന.', 'A confidential blood test to check for HIV infection.',
   'Antibodies to and/or antigen of the HIV virus.',
   'For screening, after possible exposure, or during pregnancy care.',
   'No special preparation needed; counselling is offered.', 'A blood sample is drawn from a vein; results are kept confidential.',
   '{"result":{"unit":"reactive/non-reactive"}}',
   'A reactive screening test is always confirmed with further testing before any diagnosis.',
   ARRAY['HIV'], ARRAY['CBC'], true, false)
ON CONFLICT (slug) DO NOTHING;
